import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Cinci(props) {
  const { nodes, materials } = useGLTF("/robotii/sez5.glb");
  return (
    <group {...props} dispose={null} position={[0, 20, 10]}>
      <group
        name="Body1586"
        position={[2.7082, -23.1317, -10.0516]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh
          name="Body1298"
          castShadow
          receiveShadow
          geometry={nodes.Body1298.geometry}
          material={materials["Plastic - Glossy (Black)"]}
        />
        <mesh
          name="Body1298_1"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_1.geometry}
          material={materials["Aluminum - Bead Blasted"]}
        />
        <mesh
          name="Body1298_2"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_2.geometry}
          material={materials["Opaque(51,102,178).001"]}
        />
        <mesh
          name="Body1298_3"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_3.geometry}
          material={materials["Plastic - Glossy (Green).001"]}
        />
        <mesh
          name="Body1298_4"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_4.geometry}
          material={materials["Opaque(191,191,191).001"]}
        />
        <mesh
          name="Body1298_5"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_5.geometry}
          material={materials["Opaque(255,255,255).001"]}
        />
        <mesh
          name="Body1298_6"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_6.geometry}
          material={materials["Plastic - Glossy (Red).001"]}
        />
        <mesh
          name="Body1298_7"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_7.geometry}
          material={materials["Opaque(228,233,237).001"]}
        />
        <mesh
          name="Body1298_8"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_8.geometry}
          material={materials["Opaque(198,193,188).001"]}
        />
        <mesh
          name="Body1298_9"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_9.geometry}
          material={materials["Opaque(192,192,192).001"]}
        />
        <mesh
          name="Body1298_10"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_10.geometry}
          material={materials["Opaque(63,63,63).001"]}
        />
        <mesh
          name="Body1298_11"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_11.geometry}
          material={materials["Opaque(202,209,238).001"]}
        />
        <mesh
          name="Body1298_12"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_12.geometry}
          material={materials["Opaque(203,210,239).001"]}
        />
        <mesh
          name="Body1298_13"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_13.geometry}
          material={materials["Opaque(192,192,0).001"]}
        />
        <mesh
          name="Body1298_14"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_14.geometry}
          material={materials["Opaque(229,235,237).001"]}
        />
        <mesh
          name="Body1298_15"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_15.geometry}
          material={materials["Opaque(229,229,229).001"]}
        />
        <mesh
          name="Body1298_16"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_16.geometry}
          material={materials["Opaque(165,158,150).001"]}
        />
        <mesh
          name="Body1298_17"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_17.geometry}
          material={materials["Opaque(255,0,0).001"]}
        />
        <mesh
          name="Body1298_18"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_18.geometry}
          material={materials["Opaque(64,64,64).001"]}
        />
        <mesh
          name="Body1298_19"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_19.geometry}
          material={materials["Opaque(2,61,210).001"]}
        />
        <mesh
          name="Body1298_20"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_20.geometry}
          material={materials["Opaque(221,232,255)"]}
        />
        <mesh
          name="Body1298_21"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_21.geometry}
          material={materials["Steel - Satin.001"]}
        />
        <mesh
          name="Body1298_22"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_22.geometry}
          material={materials["Opaque(153,153,153)"]}
        />
        <mesh
          name="Body1298_23"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_23.geometry}
          material={materials["Opaque(69,69,69).001"]}
        />
        <mesh
          name="Body1298_24"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_24.geometry}
          material={materials["Opaque(105,77,59).001"]}
        />
        <mesh
          name="Body1298_25"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_25.geometry}
          material={materials["Opaque(190,188,186).001"]}
        />
        <mesh
          name="Body1298_26"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_26.geometry}
          material={materials["Opaque(198,136,125).001"]}
        />
        <mesh
          name="Body1298_27"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_27.geometry}
          material={materials["Opaque(247,247,229).001"]}
        />
        <mesh
          name="Body1298_28"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_28.geometry}
          material={materials.Generic}
        />
        <mesh
          name="Body1298_29"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_29.geometry}
          material={materials["Generic.001"]}
        />
        <mesh
          name="Body1298_30"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_30.geometry}
          material={materials["Generic.003"]}
        />
        <mesh
          name="Body1298_31"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_31.geometry}
          material={materials["Generic.002"]}
        />
        <mesh
          name="Body1298_32"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_32.geometry}
          material={materials["Generic.004"]}
        />
        <mesh
          name="Body1298_33"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_33.geometry}
          material={materials["Opaque(89,89,89).001"]}
        />
        <mesh
          name="Body1298_34"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_34.geometry}
          material={materials["Opaque(204,204,204).001"]}
        />
        <mesh
          name="Body1298_35"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_35.geometry}
          material={materials["Opaque(128,128,128).001"]}
        />
        <mesh
          name="Body1298_36"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_36.geometry}
          material={materials["Opaque(221,221,13).001"]}
        />
        <mesh
          name="Body1298_37"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_37.geometry}
          material={materials["Opaque(28,28,28).001"]}
        />
        <mesh
          name="Body1298_38"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_38.geometry}
          material={materials["Opaque(79,79,79).001"]}
        />
        <mesh
          name="Body1298_39"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_39.geometry}
          material={materials["Opaque(255,255,0).001"]}
        />
        <mesh
          name="Body1298_40"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_40.geometry}
          material={materials["Opaque(211,214,211).001"]}
        />
        <mesh
          name="Body1298_41"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_41.geometry}
          material={materials["Opaque(221,221,227).001"]}
        />
        <mesh
          name="Body1298_42"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_42.geometry}
          material={materials["Opaque(158,103,51).001"]}
        />
        <mesh
          name="Body1298_43"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_43.geometry}
          material={materials["Opaque(198,198,208).001"]}
        />
        <mesh
          name="Body1298_44"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_44.geometry}
          material={materials["Opaque(255,242,232)"]}
        />
        <mesh
          name="Body1298_45"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_45.geometry}
          material={materials["Opaque(160,160,160).001"]}
        />
        <mesh
          name="Body1298_46"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_46.geometry}
          material={materials["Opaque(46,46,46)"]}
        />
        <mesh
          name="Body1298_47"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_47.geometry}
          material={materials["Opaque(255,199,168)"]}
        />
        <mesh
          name="Body1298_48"
          castShadow
          receiveShadow
          geometry={nodes.Body1298_48.geometry}
          material={materials["Aluminum - Anodized Rough (Grey)"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/robotii/sez5.glb");
