/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SingleRoom_update(props) {
  const { nodes, materials } = useGLTF("/singleRoom_update.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model004"
        position={[-2.7936, 4.5294, -1.8616]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.0334}
      >
        <mesh
          name="Object_2"
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["20221231_1431271384153216"]}
        />
        <mesh
          name="Object_5"
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials["20221231_143220"]}
        />
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials["20221231_1432201"]}
        />
        <mesh
          name="Object_3"
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["20221231_143201"]}
        />
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials["20221231_1432011"]}
        />
      </group>
      <group
        name="Group001003"
        position={[-1.6419, 4.2538, -1.5629]}
        rotation={[0, 0.4615, 0]}
        scale={0.0039}
      >
        <mesh
          name="Box001"
          castShadow
          receiveShadow
          geometry={nodes.Box001.geometry}
          material={materials["vray_Material #31"]}
          position={[0.8003, 1.011, 11.1466]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          name="Box006"
          castShadow
          receiveShadow
          geometry={nodes.Box006.geometry}
          material={materials["vray_Material #31"]}
          position={[0.503, 38.9534, -0.0655]}
          scale={[1.066, 1, 0.8609]}
        />
      </group>
      <group
        name="Sketchfab_model005"
        position={[-2.6938, 4.2409, -1.6096]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          name="Tool_box1_Tool_box_plastic_0002"
          castShadow
          receiveShadow
          geometry={nodes.Tool_box1_Tool_box_plastic_0002.geometry}
          material={materials["headphones.001"]}
          position={[-0.1794, 0.1041, -0.112]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.5276}
        />
        <mesh
          name="Tool_box1_Tool_box_polymer_0003"
          castShadow
          receiveShadow
          geometry={nodes.Tool_box1_Tool_box_polymer_0003.geometry}
          material={materials.box_portocala}
          position={[-0.1794, 0.1041, -0.112]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.5276}
        />
      </group>
      <group
        name="PortalGun"
        position={[-2.7748, 4.5646, -1.3923]}
        rotation={[1.6298, 0.248, -0.236]}
        scale={0.0009}
      >
        <group name="Cube_1" position={[27.4603, -0.0001, -2.78]}>
          <mesh
            name="Mesh033"
            castShadow
            receiveShadow
            geometry={nodes.Mesh033.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Mesh033_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh033_1.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <mesh
          name="Cylinder008"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials["Material.008"]}
          position={[-114.7587, -0.0001, 14.0537]}
          rotation={[0, 1.5705, 0]}
        />
        <mesh
          name="Cylinder_2"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Material.004"]}
          position={[69.0867, -0.0001, 2.1568]}
          rotation={[0, -0.4363, 0]}
        />
        <mesh
          name="Subdivision_Surface"
          castShadow
          receiveShadow
          geometry={nodes.Subdivision_Surface.geometry}
          material={materials["Material.013"]}
          position={[-22.2892, 0.0001, 14.0541]}
        />
        <mesh
          name="Tube"
          castShadow
          receiveShadow
          geometry={nodes.Tube.geometry}
          material={materials["Material.003"]}
          position={[-47.2892, -0.0001, -0.6993]}
        />
        <mesh
          name="Cylinder_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Material.004"]}
          position={[70.5146, 0.0001, -0.9047]}
          rotation={[0, -0.4363, 0]}
        />
        <mesh
          name="Subdivision_Surface_2"
          castShadow
          receiveShadow
          geometry={nodes.Subdivision_Surface_2.geometry}
          material={materials["Material.011"]}
          position={[-47.3249, 0, -43.7813]}
          rotation={[0.4705, -1.0935, -0.4851]}
        />
        <mesh
          name="Extrude"
          castShadow
          receiveShadow
          geometry={nodes.Extrude.geometry}
          material={materials["Material.007"]}
          position={[35.7029, 0, -9.2311]}
          rotation={[0, 1.1694, -Math.PI / 2]}
        />
        <mesh
          name="Capsule"
          castShadow
          receiveShadow
          geometry={nodes.Capsule.geometry}
          material={materials["20221231_1431271384153216"]}
          position={[-47.289, 0, 21.5598]}
        />
      </group>
      <group
        name="Sketchfab_model006"
        position={[-2.8149, 4.4762, -2.6907]}
        rotation={[-Math.PI / 2, 0, 1.2025]}
        scale={0.0001}
      >
        <group
          name="3526a8abc29342dd86354e398e5cd46dfbx002"
          position={[-0.0001, 0.0014, 0.0011]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <group name="RootNode005" position={[-0.0011, 0.0012, -0.0003]}>
            <group
              name="Cube041"
              position={[-1.662, 2355.1301, -307.2387]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube017_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cube017_Black_base_0002.geometry}
                material={nodes.Cube017_Black_base_0002.material}
                position={[0, 0, -0.0001]}
              />
            </group>
            <group
              name="Cube043"
              position={[973.7887, 2313.2161, -334.7216]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[27.1811, 24.4487, 43.5728]}
            >
              <group
                name="Cube042"
                position={[-0.0377, 0.0001, 1.9494]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[4.0902, 3.679, 2.295]}
              >
                <mesh
                  name="Cube013_White_metal_boxes_0002"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube013_White_metal_boxes_0002.geometry}
                  material={nodes.Cube013_White_metal_boxes_0002.material}
                />
              </group>
            </group>
            <group
              name="Cube044"
              position={[-0.0012, 800.4407, -0.0002]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube009_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cube009_Black_base_0002.geometry}
                material={materials["red.001"]}
              />
            </group>
            <group
              name="Cube045"
              position={[-0.0001, 311.1319, 1222.3152]}
              rotation={[1.1352, 0, -Math.PI]}
              scale={[-220.5066, -10.5837, -139.8365]}
            >
              <mesh
                name="Cube008_White_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cube008_White_metal_0002.geometry}
                material={nodes.Cube008_White_metal_0002.material}
              />
            </group>
            <group
              name="Cube046"
              position={[-0.0012, 680.509, -0.0002]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube004_Black_base_table_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cube004_Black_base_table_0002.geometry}
                material={materials["premiu_verde.001"]}
              />
            </group>
            <group
              name="Cube047"
              position={[-0.0012, 800.4407, -0.0002]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 100, 122.7162]}
            >
              <mesh
                name="Cube003_White_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cube003_White_metal_0002.geometry}
                material={materials["headphones.002"]}
              />
            </group>
            <group
              name="Cube048"
              position={[-0.0011, 394.0774, -0.0002]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube002_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cube002_Black_base_0002.geometry}
                material={nodes.Cube002_Black_base_0002.material}
              />
            </group>
            <group
              name="Cube049"
              position={[-1095.8644, 394.0774, 19.0667]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube001_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cube001_Black_base_0002.geometry}
                material={materials["Material.002"]}
              />
            </group>
            <group
              name="Cube050"
              position={[-0.0011, 394.0774, -0.0002]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cube_Black_base_0002.geometry}
                material={materials["headphones.002"]}
              />
            </group>
            <group
              name="Cylinder009"
              position={[-1.662, 2494.427, -100.9062]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[89.8313, 81.5231, 89.8313]}
            >
              <mesh
                name="Cylinder024_Shiny_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder024_Shiny_metal_0002.geometry}
                material={nodes.Cylinder024_Shiny_metal_0002.material}
                position={[0, 0, -0.0001]}
              />
            </group>
            <group
              name="Cylinder032"
              position={[-1.662, 2300.0754, -100.9062]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[89.0194, 83.1528, 89.0194]}
            >
              <mesh
                name="Cylinder023_Shiny_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder023_Shiny_metal_0002.geometry}
                material={nodes.Cylinder023_Shiny_metal_0002.material}
              />
            </group>
            <group
              name="Cylinder033"
              position={[-0.0012, 800.4407, -0.0002]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder022_Shiny_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder022_Shiny_metal_0002.geometry}
                material={nodes.Cylinder022_Shiny_metal_0002.material}
              />
            </group>
            <group
              name="Cylinder034"
              position={[0.0003, 800.4407, -47.4391]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder020_White_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020_White_metal_0002.geometry}
                material={nodes.Cylinder020_White_metal_0002.material}
              />
            </group>
            <group
              name="Cylinder035"
              position={[-0.0241, 559.4916, -919.0583]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[130.1945, 130.1944, 107.5047]}
            >
              <mesh
                name="Cylinder017_Black_resin_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder017_Black_resin_0002.geometry}
                material={nodes.Cylinder017_Black_resin_0002.material}
              />
            </group>
            <group
              name="Cylinder036"
              position={[-0.0241, 525.4155, -919.0583]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={129.502}
            >
              <mesh
                name="Cylinder014_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder014_Black_base_0002.geometry}
                material={nodes.Cylinder014_Black_base_0002.material}
              />
            </group>
            <group
              name="Cylinder037"
              position={[-0.0241, 582.2905, -919.0583]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder012_White_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder012_White_metal_0002.geometry}
                material={nodes.Cylinder012_White_metal_0002.material}
              />
            </group>
            <group
              name="Cylinder038"
              position={[-0.0251, 508.8292, 858.868]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[29.2106, 29.2106, 14.9795]}
            >
              <mesh
                name="Cylinder010_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder010_Black_base_0002.geometry}
                material={nodes.Cylinder010_Black_base_0002.material}
                position={[0, 0, 0.0001]}
              />
            </group>
            <group
              name="Cylinder039"
              position={[403.2547, 619.3001, -48.5637]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder005_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder005_Black_base_0002.geometry}
                material={nodes.Cylinder005_Black_base_0002.material}
              />
            </group>
            <group
              name="Cylinder040"
              position={[-402.13, 584.8333, -48.5637]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 99.8831, 100]}
            >
              <mesh
                name="Cylinder004_Shiny_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004_Shiny_metal_0002.geometry}
                material={nodes.Cylinder004_Shiny_metal_0002.material}
              />
            </group>
            <group
              name="Cylinder041"
              position={[403.2552, 584.8333, -48.5617]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 99.8831, 100]}
            >
              <mesh
                name="Cylinder003_Shiny_metal_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003_Shiny_metal_0002.geometry}
                material={nodes.Cylinder003_Shiny_metal_0002.material}
              />
            </group>
            <group
              name="Cylinder042"
              position={[-402.1306, 603.3726, -1136.5465]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder002_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder002_Black_base_0002.geometry}
                material={nodes.Cylinder002_Black_base_0002.material}
              />
            </group>
            <group
              name="Cylinder043"
              position={[403.2542, 603.3726, -1136.5485]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder001_Black_base_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001_Black_base_0002.geometry}
                material={nodes.Cylinder001_Black_base_0002.material}
              />
            </group>
            <group
              name="Cylinder044"
              position={[-0.0012, 680.509, -0.0002]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder_Shiny_metal_gold001_0002"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_Shiny_metal_gold001_0002.geometry}
                material={nodes.Cylinder_Shiny_metal_gold001_0002.material}
              />
            </group>
          </group>
        </group>
      </group>
      <group
        name="Acer_Travelmate_P645002"
        position={[-1.7207, 4.5737, -2.7333]}
        rotation={[-Math.PI, 0.6109, -Math.PI]}
        scale={0.0021}
      >
        <group
          name="monitor002"
          position={[47.6579, 64.5842, 72.9591]}
          rotation={[-2.7235, -0.5692, -2.9065]}
          scale={9.9832}
        >
          <mesh
            name="Mesh052"
            castShadow
            receiveShadow
            geometry={nodes.Mesh052.geometry}
            material={materials["gray_plastic.001"]}
          />
          <mesh
            name="Mesh052_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh052_1.geometry}
            material={materials["display.001"]}
          />
          <mesh
            name="Mesh052_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh052_2.geometry}
            material={materials["monitor_plastic.004"]}
          />
          <mesh
            name="Mesh052_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh052_3.geometry}
            material={materials["logo_monitor_bottom.003"]}
          />
        </group>
        <group
          name="bottom_corpus002"
          position={[-16.9872, -21.7251, 11.9337]}
          rotation={[-Math.PI / 2, 0, -0.9599]}
          scale={-9.9832}
        >
          <mesh
            name="Mesh051"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051.geometry}
            material={materials["monitor_plastic.002"]}
          />
          <mesh
            name="Mesh051_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_1.geometry}
            material={materials["gray_plastic.001"]}
          />
          <mesh
            name="Mesh051_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_2.geometry}
            material={materials["keyboard.002"]}
          />
          <mesh
            name="Mesh051_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_3.geometry}
            material={materials["sensor.001"]}
          />
          <mesh
            name="Mesh051_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_4.geometry}
            material={materials["socket_USB.001"]}
          />
          <mesh
            name="Mesh051_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_5.geometry}
            material={materials["socket_power.001"]}
          />
          <mesh
            name="Mesh051_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_6.geometry}
            material={materials["socket_steel.001"]}
          />
          <mesh
            name="Mesh051_7"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_7.geometry}
            material={materials["headphones.001"]}
          />
          <mesh
            name="Mesh051_8"
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_8.geometry}
            material={materials["logo.001"]}
          />
        </group>
      </group>
      <group
        name="Cylinder006"
        position={[-2.8523, 5.5875, -1.9021]}
        rotation={[0, -0.1411, 0]}
        scale={0.3359}
      >
        <mesh
          name="Cylinder005"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials.metal}
        />
        <mesh
          name="Cylinder005_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials["window glass"]}
        />
        <mesh
          name="Cylinder005_2"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_2.geometry}
          material={materials.red}
        />
        <mesh
          name="Cylinder005_3"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_3.geometry}
          material={materials.white}
        />
        <mesh
          name="Cylinder005_4"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_4.geometry}
          material={materials["white.Smoke"]}
        />
      </group>
      <mesh
        name="robofeu002"
        castShadow
        receiveShadow
        geometry={nodes.robofeu002.geometry}
        material={materials.premiu_verde}
        position={[-2.9097, 5.3087, -1.5766]}
        rotation={[-Math.PI, 0.0437, -Math.PI]}
        scale={0.0025}
      />
      <mesh
        name="robofeu003"
        castShadow
        receiveShadow
        geometry={nodes.robofeu003.geometry}
        material={materials.premiu_verde}
        position={[-2.9093, 5.3087, -2.2287]}
        rotation={[-Math.PI, 0.3848, -Math.PI]}
        scale={0.0025}
      />
      <mesh
        name="imagetostl_mesh006"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh006.geometry}
        material={materials.metal}
        position={[-2.852, 4.0566, -2.133]}
        rotation={[-Math.PI, 0.1522, -Math.PI]}
        scale={0.0012}
      />
      <mesh
        name="dingding_Spardose_V11"
        castShadow
        receiveShadow
        geometry={nodes.dingding_Spardose_V11.geometry}
        material={nodes.dingding_Spardose_V11.material}
        position={[-2.7916, 4.4322, -1.4228]}
        rotation={[0, 1.3058, 0]}
        scale={0.0004}
      />
      <mesh
        name="imagetostl_mesh008"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh008.geometry}
        material={materials.metal}
        position={[-2.7994, 4.1006, -2.129]}
        rotation={[-Math.PI, 0.3023, -Math.PI]}
        scale={0.0012}
      />
      <mesh
        name="Cube008"
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-3.099, 5, -2]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name="Cube013"
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[-2, 5, -3.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name="Cube040"
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials.cardboard}
        position={[-2, 4.01, -2]}
        scale={[1, 0.01, 1]}
      />
      <mesh
        name="imagetostl_mesh007"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh007.geometry}
        material={materials.metal}
        position={[-2.7507, 4.0566, -2.1254]}
        rotation={[-Math.PI, 0.1522, -Math.PI]}
        scale={0.0012}
      />
      <mesh
        name="Body"
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials.phong1}
        position={[-2.3627, 4.9414, -2.9535]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0539}
      />
      <mesh
        name="Body001"
        castShadow
        receiveShadow
        geometry={nodes.Body001.geometry}
        material={materials.phong1}
        position={[-1.5024, 4.9414, -2.9535]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0539}
      />
      <mesh
        name="imagetostl_mesh011"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh011.geometry}
        material={materials.metal}
        position={[-1.5969, 4.132, -2.7648]}
        rotation={[0, 1.3428, 0]}
        scale={0.0015}
      />
      <mesh
        name="imagetostl_mesh009"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh009.geometry}
        material={materials.metal}
        position={[-1.5969, 4.0744, -2.8337]}
        rotation={[0, 1.4929, 0]}
        scale={0.0015}
      />
      <mesh
        name="imagetostl_mesh010"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh010.geometry}
        material={materials.metal}
        position={[-1.5969, 4.0744, -2.7009]}
        rotation={[0, 1.4929, 0]}
        scale={0.0015}
      />
      <mesh
        name="Cube029"
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials["vray_Material #31"]}
        position={[-2.9054, 5.2912, -1.8903]}
        rotation={[0, 1.57, 0]}
        scale={[0.3988, 0.0158, 0.0874]}
      />
      <mesh
        name="Router002"
        castShadow
        receiveShadow
        geometry={nodes.Router002.geometry}
        material={materials.router}
        position={[-2.8876, 4.5258, -2.3757]}
        rotation={[Math.PI / 2, 0, -1.4392]}
        scale={0.01}
      />
      <mesh
        name="Router003"
        castShadow
        receiveShadow
        geometry={nodes.Router003.geometry}
        material={materials.router}
        position={[-1.2198, 4.5579, -2.8557]}
        rotation={[Math.PI / 2, 0, 0.2545]}
        scale={0.01}
      />
      <mesh
        name="clester004"
        castShadow
        receiveShadow
        geometry={nodes.clester004.geometry}
        material={materials.router}
        position={[-1.3254, 4.5259, -2.6631]}
        rotation={[Math.PI, -1.3282, Math.PI]}
      />
      <mesh
        name="Screen"
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={materials.Material}
        position={[-2.3627, 4.9414, -2.9535]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0539}
      />
      <mesh
        name="desk010"
        castShadow
        receiveShadow
        geometry={nodes.desk010.geometry}
        material={materials.tabla}
        position={[-2.8042, 4.3315, -1.4131]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.1743, 0.2196, 0.2196]}
      />
      <mesh
        name="desk011"
        castShadow
        receiveShadow
        geometry={nodes.desk011.geometry}
        material={materials.tabla}
        position={[-2.8042, 4.3315, -2.1185]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.1743, 0.2196, 0.2196]}
      />
      <mesh
        name="desk002"
        castShadow
        receiveShadow
        geometry={nodes.desk002.geometry}
        material={materials.tabla}
        position={[-2.8042, 4.3315, -2.7342]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.1358, 0.2196, 0.2196]}
      />
      <mesh
        name="desk012"
        castShadow
        receiveShadow
        geometry={nodes.desk012.geometry}
        material={materials.tabla}
        position={[-1.4982, 4.3514, -2.7892]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.2196}
      />
      <mesh
        name="lampa_perete010"
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete010.geometry}
        material={materials.lampa_pereti}
        position={[-2.2249, 5.5242, -2.8578]}
        scale={0.0093}
      />
      <mesh
        name="lampa_perete011"
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete011.geometry}
        material={materials.lampa_pereti}
        position={[-1.5275, 5.5242, -2.8578]}
        scale={0.0093}
      />
      <mesh
        name="Screen001"
        castShadow
        receiveShadow
        geometry={nodes.Screen001.geometry}
        material={materials["Material.001"]}
        position={[-1.5024, 4.9414, -2.9535]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0539}
      />
    </group>
  );
}

useGLTF.preload("/singleRoom_update.glb");
