/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Room2(props) {
  const { nodes, materials } = useGLTF("/scenes/sez2_room.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Group003"
        position={[0.7947, 0.5134, -0.8382]}
        rotation={[-1.8727, -Math.PI / 2, 0]}
        scale={[0.0217, 0.0217, 0.0256]}
      >
        <group name="Group001" position={[-13.5455, -0.1372, 0]}>
          <mesh
            name="Wheel003"
            castShadow
            receiveShadow
            geometry={nodes.Wheel003.geometry}
            material={materials["headphones.001"]}
            position={[0.6025, -0.4058, -3.3731]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Veshalka001"
            castShadow
            receiveShadow
            geometry={nodes.Veshalka001.geometry}
            material={materials.metal}
            position={[0.4183, -0.0548, 3.1405]}
            rotation={[1.5583, 0.9486, -1.5554]}
            scale={-0.0917}
          />
          <mesh
            name="Wheel002"
            castShadow
            receiveShadow
            geometry={nodes.Wheel002.geometry}
            material={materials["headphones.001"]}
            position={[0.5969, -0.4058, 3.3731]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={-1}
          />
        </group>
        <mesh
          name="Line001"
          castShadow
          receiveShadow
          geometry={nodes.Line001.geometry}
          material={materials.cardboard}
          position={[-0.5984, 1.7409, -1.6991]}
        />
        <mesh
          name="Line001001"
          castShadow
          receiveShadow
          geometry={nodes.Line001001.geometry}
          material={materials["socket_power.001"]}
          position={[-0.5984, 1.7409, -1.6991]}
        />
      </group>
      <mesh
        name="Cube001"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.cardboard}
        position={[0, 0.0785, 0]}
        scale={[1, 0.0312, 1]}
      />
      <mesh
        name="Cube012"
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-2, 1, 0]}
      />
      <mesh
        name="Cube004"
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0, 1, -2]}
      />
      <mesh
        name="surusurubelnita001"
        castShadow
        receiveShadow
        geometry={nodes.surusurubelnita001.geometry}
        material={nodes.surusurubelnita001.material}
        position={[-0.7565, 0.9637, -0.6237]}
        rotation={[0.0732, 0.6158, 1.4445]}
        scale={1.0594}
      />
      <mesh
        name="cardboard_box_01_1k"
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_01_1k.geometry}
        material={materials.cardboard}
        position={[-0.8049, 0.579, -0.7041]}
        scale={0.8339}
      />
      <mesh
        name="cardboard_box_01_1k001"
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_01_1k001.geometry}
        material={materials.cardboard}
        position={[-0.8049, 0.1983, -0.3758]}
        scale={0.8339}
      />
      <mesh
        name="cardboard_box_01_1k002"
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_01_1k002.geometry}
        material={materials.cardboard}
        position={[-0.8049, 0.1983, -0.7762]}
        scale={0.8339}
      />
      <mesh
        name="cardboard_box_01_1k003"
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_01_1k003.geometry}
        material={materials.cardboard}
        position={[-0.8049, 1.328, -0.7617]}
        scale={0.8339}
      />
      <mesh
        name="Cube022"
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials.router}
        position={[-0.8542, 0.78, 0.1623]}
        rotation={[-1.0676, 0.3512, 1.5015]}
        scale={0.3328}
      />
      <mesh
        name="bend1001"
        castShadow
        receiveShadow
        geometry={nodes.bend1001.geometry}
        material={materials.router}
        position={[-0.7784, 0.5835, 0.4622]}
        scale={0.0055}
      />
      <mesh
        name="clester"
        castShadow
        receiveShadow
        geometry={nodes.clester.geometry}
        material={materials.tabla}
        position={[0.0229, 0.6162, 0.5399]}
      />
      <mesh
        name="measuring_tape_01_1k001"
        castShadow
        receiveShadow
        geometry={nodes.measuring_tape_01_1k001.geometry}
        material={materials.tabla}
        position={[-0.5978, 0.7466, 0.3175]}
        scale={1.0663}
      />
      <mesh
        name="screwdriver002"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver002.geometry}
        material={materials.tabla}
        position={[-0.0731, 0.618, 0.3074]}
        rotation={[0, 1.1641, 0]}
        scale={0.0008}
      />
      <mesh
        name="steel_frame_shelves_01_1k"
        castShadow
        receiveShadow
        geometry={nodes.steel_frame_shelves_01_1k.geometry}
        material={materials.tabla}
        position={[-0.7869, 0.1012, -0.5503]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.7445}
      />
      <mesh
        name="desk"
        castShadow
        receiveShadow
        geometry={nodes.desk.geometry}
        material={materials.tabla}
        position={[0.0261, 0.4431, 0.3927]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.2196}
      />
      <mesh
        name="desk001"
        castShadow
        receiveShadow
        geometry={nodes.desk001.geometry}
        material={materials.tabla}
        position={[0.4071, 0.4414, 0.3492]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.2196}
      />
      <mesh
        name="katana"
        castShadow
        receiveShadow
        geometry={nodes.katana.geometry}
        material={materials.katarama}
        position={[-0.7444, 0.3137, 0.2466]}
        rotation={[1.6487, -0.0346, 0.326]}
      />
      <mesh
        name="lampa"
        castShadow
        receiveShadow
        geometry={nodes.lampa.geometry}
        material={materials.lampa_pereti}
        position={[-0.6159, 0.7415, -0.0687]}
        rotation={[0, 1.1222, 0]}
        scale={0.7184}
      />
      <mesh
        name="lampa_perete"
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete.geometry}
        material={materials["lampa_pereti.001"]}
        position={[-0.2719, 1.3954, -0.8674]}
        scale={0.0093}
      />
      <mesh
        name="lampa_perete001"
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete001.geometry}
        material={materials["lampa_pereti.001"]}
        position={[0.4255, 1.3954, -0.8674]}
        scale={0.0093}
      />
      <mesh
        name="canapea"
        castShadow
        receiveShadow
        geometry={nodes.canapea.geometry}
        material={materials.banca}
        position={[0.0099, 0.1226, -0.8262]}
        scale={[0.0242, 0.0342, 0.0242]}
      />
      <mesh
        name="bench_vice_01_1k001"
        castShadow
        receiveShadow
        geometry={nodes.bench_vice_01_1k001.geometry}
        material={materials.merenghina}
        position={[-0.6611, 0.7399, 0.9569]}
        scale={0.6206}
      />
      <mesh
        name="Drill_01_1k001"
        castShadow
        receiveShadow
        geometry={nodes.Drill_01_1k001.geometry}
        material={materials.boromiro_masina}
        position={[-0.723, 0.7808, 0.5783]}
        rotation={[Math.PI / 2, 0, -1.1752]}
        scale={1.2866}
      />
    </group>
  );
}

useGLTF.preload("/scenes/sez2_room.glb");
