/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Room4(props) {
  const { nodes, materials } = useGLTF("/scenes/sez4_room.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model001"
        position={[-0.4993, 2.4915, -2.8358]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.0002}
      >
        <group
          name="3526a8abc29342dd86354e398e5cd46dfbx"
          position={[0.0002, 0.0004, -0.0009]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <group name="RootNode001" position={[0.0002, 0, -0.001]}>
            <group
              name="Cube"
              position={[0.0002, 394.0781, -0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube_Black_base_0.geometry}
                material={materials["headphones.001"]}
              />
            </group>
            <group
              name="Cube003"
              position={[-1095.8621, 394.0781, 19.0654]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube001_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube001_Black_base_0.geometry}
                material={materials["Material.006"]}
              />
            </group>
            <group
              name="Cube007"
              position={[0.0002, 394.0781, -0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube002_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube002_Black_base_0.geometry}
                material={nodes.Cube002_Black_base_0.material}
              />
            </group>
            <group
              name="Cube009"
              position={[0.0002, 800.4414, -0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 100, 122.7162]}
            >
              <mesh
                name="Cube003_White_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube003_White_metal_0.geometry}
                material={materials["headphones.001"]}
              />
            </group>
            <group
              name="Cube016"
              position={[0.0002, 680.5068, -0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube004_Black_base_table_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube004_Black_base_table_0.geometry}
                material={materials.premiu_verde}
              />
            </group>
            <group
              name="Cube023"
              position={[0.0002, 311.1328, 1222.3154]}
              rotation={[1.1352, 0, -Math.PI]}
              scale={[-220.5066, -10.5837, -139.8365]}
            >
              <mesh
                name="Cube008_White_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube008_White_metal_0.geometry}
                material={nodes.Cube008_White_metal_0.material}
                position={[0, -0.0001, 0]}
              />
            </group>
            <group
              name="Cube024"
              position={[0.0002, 800.4414, -0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube009_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube009_Black_base_0.geometry}
                material={materials.red}
              />
            </group>
            <group
              name="Cube025"
              position={[973.7898, 2313.2139, -334.7217]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[27.1811, 24.4487, 43.5728]}
            >
              <group
                name="Cube026"
                position={[-0.0376, 0, 1.9494]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[4.0902, 3.679, 2.295]}
              >
                <mesh
                  name="Cube013_White_metal_boxes_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube013_White_metal_boxes_0.geometry}
                  material={nodes.Cube013_White_metal_boxes_0.material}
                />
              </group>
            </group>
            <group
              name="Cube027"
              position={[-1.6602, 2355.1318, -307.2393]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cube017_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube017_Black_base_0.geometry}
                material={nodes.Cube017_Black_base_0.material}
              />
            </group>
            <group
              name="Cylinder"
              position={[0.0002, 680.5068, -0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder_Shiny_metal_gold001_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_Shiny_metal_gold001_0.geometry}
                material={nodes.Cylinder_Shiny_metal_gold001_0.material}
              />
            </group>
            <group
              name="Cylinder001"
              position={[403.2556, 603.374, -1136.5479]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder001_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001_Black_base_0.geometry}
                material={nodes.Cylinder001_Black_base_0.material}
              />
            </group>
            <group
              name="Cylinder002"
              position={[-402.1296, 603.374, -1136.5479]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder002_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder002_Black_base_0.geometry}
                material={nodes.Cylinder002_Black_base_0.material}
              />
            </group>
            <group
              name="Cylinder003"
              position={[403.2556, 584.835, -48.5625]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 99.8831, 100]}
            >
              <mesh
                name="Cylinder003_Shiny_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003_Shiny_metal_0.geometry}
                material={nodes.Cylinder003_Shiny_metal_0.material}
              />
            </group>
            <group
              name="Cylinder004"
              position={[-402.1296, 584.835, -48.5625]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 99.8831, 100]}
            >
              <mesh
                name="Cylinder004_Shiny_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004_Shiny_metal_0.geometry}
                material={nodes.Cylinder004_Shiny_metal_0.material}
              />
            </group>
            <group
              name="Cylinder005"
              position={[403.2556, 619.2979, -48.5635]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder005_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder005_Black_base_0.geometry}
                material={nodes.Cylinder005_Black_base_0.material}
              />
            </group>
            <group
              name="Cylinder010"
              position={[-0.0244, 508.8281, 858.8682]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[29.2106, 29.2106, 14.9795]}
            >
              <mesh
                name="Cylinder010_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder010_Black_base_0.geometry}
                material={nodes.Cylinder010_Black_base_0.material}
                position={[0, 0.0001, 0]}
              />
            </group>
            <group
              name="Cylinder012"
              position={[-0.0244, 582.29, -919.0586]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder012_White_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder012_White_metal_0.geometry}
                material={nodes.Cylinder012_White_metal_0.material}
              />
            </group>
            <group
              name="Cylinder014"
              position={[-0.0244, 525.415, -919.0586]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={129.502}
            >
              <mesh
                name="Cylinder014_Black_base_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder014_Black_base_0.geometry}
                material={nodes.Cylinder014_Black_base_0.material}
              />
            </group>
            <group
              name="Cylinder017"
              position={[-0.0244, 559.4912, -919.0586]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[130.1945, 130.1944, 107.5048]}
            >
              <mesh
                name="Cylinder017_Black_resin_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder017_Black_resin_0.geometry}
                material={nodes.Cylinder017_Black_resin_0.material}
              />
            </group>
            <group
              name="Cylinder020"
              position={[0.0002, 800.4414, -47.4385]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder020_White_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020_White_metal_0.geometry}
                material={nodes.Cylinder020_White_metal_0.material}
              />
            </group>
            <group
              name="Cylinder022"
              position={[0.0002, 800.4414, -0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                name="Cylinder022_Shiny_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder022_Shiny_metal_0.geometry}
                material={nodes.Cylinder022_Shiny_metal_0.material}
              />
            </group>
            <group
              name="Cylinder023"
              position={[-1.6602, 2300.0742, -100.9072]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[89.0194, 83.1527, 89.0194]}
            >
              <mesh
                name="Cylinder023_Shiny_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder023_Shiny_metal_0.geometry}
                material={nodes.Cylinder023_Shiny_metal_0.material}
              />
            </group>
            <group
              name="Cylinder024"
              position={[-1.6602, 2494.4268, -100.9072]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[89.8313, 81.5231, 89.8313]}
            >
              <mesh
                name="Cylinder024_Shiny_metal_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder024_Shiny_metal_0.geometry}
                material={nodes.Cylinder024_Shiny_metal_0.material}
              />
            </group>
          </group>
        </group>
      </group>
      <group
        name="Sketchfab_model002"
        position={[-0.2992, 2.2418, -2.6656]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          name="Tool_boxfbx001"
          position={[-0.4257, 0.2174, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Tool_box1_Tool_box_polymer_0001"
            castShadow
            receiveShadow
            geometry={nodes.Tool_box1_Tool_box_polymer_0001.geometry}
            material={materials.box_portocala}
            position={[0.2464, -0.112, 0.1044]}
            scale={0.5276}
          />
          <mesh
            name="Tool_box1_Tool_box_plastic_0001"
            castShadow
            receiveShadow
            geometry={nodes.Tool_box1_Tool_box_plastic_0001.geometry}
            material={materials["headphones.001"]}
            position={[0.2464, -0.112, 0.1134]}
            scale={0.5276}
          />
        </group>
      </group>
      <group
        name="Acer_Travelmate_P645"
        position={[0.3214, 2.554, -2.7333]}
        rotation={[-Math.PI, 0.6109, -Math.PI]}
        scale={0.0021}
      >
        <group
          name="monitor"
          position={[47.6579, 64.5842, 72.959]}
          rotation={[-2.7235, -0.5692, -2.9065]}
          scale={9.9832}
        >
          <mesh
            name="Mesh023"
            castShadow
            receiveShadow
            geometry={nodes.Mesh023.geometry}
            material={materials["gray_plastic.001"]}
          />
          <mesh
            name="Mesh023_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh023_1.geometry}
            material={materials["display.001"]}
          />
          <mesh
            name="Mesh023_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh023_2.geometry}
            material={materials["monitor_plastic.004"]}
          />
          <mesh
            name="Mesh023_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh023_3.geometry}
            material={materials["logo_monitor_bottom.003"]}
          />
        </group>
        <group
          name="bottom_corpus"
          position={[-16.9872, -21.7253, 11.9336]}
          rotation={[-Math.PI / 2, 0, -0.9599]}
          scale={-9.9832}
        >
          <mesh
            name="Mesh022"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022.geometry}
            material={materials["monitor_plastic.002"]}
          />
          <mesh
            name="Mesh022_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_1.geometry}
            material={materials["gray_plastic.001"]}
          />
          <mesh
            name="Mesh022_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_2.geometry}
            material={materials["keyboard.002"]}
          />
          <mesh
            name="Mesh022_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_3.geometry}
            material={materials["sensor.001"]}
          />
          <mesh
            name="Mesh022_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_4.geometry}
            material={materials["socket_USB.001"]}
          />
          <mesh
            name="Mesh022_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_5.geometry}
            material={materials["socket_power.001"]}
          />
          <mesh
            name="Mesh022_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_6.geometry}
            material={materials["socket_steel.001"]}
          />
          <mesh
            name="Mesh022_7"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_7.geometry}
            material={materials["headphones.001"]}
          />
          <mesh
            name="Mesh022_8"
            castShadow
            receiveShadow
            geometry={nodes.Mesh022_8.geometry}
            material={materials["logo.001"]}
          />
        </group>
      </group>
      <mesh
        name="Perfil2020008"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020008.geometry}
        material={materials.metal}
        position={[-0.7576, 2.8647, -1.554]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0002}
      />
      <mesh
        name="Perfil2020009"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020009.geometry}
        material={materials.metal}
        position={[-0.7121, 2.8626, -1.6203]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0002}
      />
      <mesh
        name="Perfil2020007"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020007.geometry}
        material={materials.metal}
        position={[-0.8626, 2.8618, -1.5884]}
        rotation={[Math.PI / 2, 0, 0.1346]}
        scale={0.0002}
      />
      <mesh
        name="Perfil2020010"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020010.geometry}
        material={materials.metal}
        position={[-0.7905, 2.903, -1.5213]}
        rotation={[Math.PI / 2, 0, 2.6529]}
        scale={0.0002}
      />
      <mesh
        name="Perfil2020011"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020011.geometry}
        material={materials.metal}
        position={[-0.7905, 2.903, -1.8266]}
        rotation={[Math.PI / 2, 0, -0.8511]}
        scale={0.0002}
      />
      <mesh
        name="Perfil2020012"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020012.geometry}
        material={materials.metal}
        position={[-0.7905, 2.9462, -1.6845]}
        rotation={[Math.PI / 2, 0, -Math.PI / 9]}
        scale={0.0002}
      />
      <group
        name="Cylinder007"
        position={[-0.0435, 2.7805, -2.6939]}
        rotation={[0, -1.1985, 0]}
        scale={0.3359}
      >
        <mesh
          name="Cylinder002_1"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.metal}
        />
        <mesh
          name="Cylinder002_2"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_2.geometry}
          material={materials["window glass"]}
        />
        <mesh
          name="Cylinder002_3"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_3.geometry}
          material={materials.red}
        />
        <mesh
          name="Cylinder002_4"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_4.geometry}
          material={materials.white}
        />
        <mesh
          name="Cylinder002_5"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_5.geometry}
          material={materials["white.Smoke"]}
        />
      </group>
      <mesh
        name="robofeu001"
        castShadow
        receiveShadow
        geometry={nodes.robofeu001.geometry}
        material={materials.premiu_verde}
        position={[0.6677, 3.1102, -2.9128]}
        rotation={[-Math.PI, 1.2211, -Math.PI]}
        scale={0.0025}
      />
      <mesh
        name="Cube006"
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[0, 3, -3.094]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name="Cube028"
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials.cardboard}
        position={[0, 2.0046, -2]}
        scale={[1, 0.01, 1]}
      />
      <mesh
        name="Cube051"
        castShadow
        receiveShadow
        geometry={nodes.Cube051.geometry}
        material={nodes.Cube051.material}
        position={[-1, 3, -2]}
        scale={[0.01, 1, 1]}
      />
      <mesh
        name="robofeu"
        castShadow
        receiveShadow
        geometry={nodes.robofeu.geometry}
        material={materials.premiu_verde}
        position={[0.2029, 3.1102, -2.9128]}
        rotation={[0, 1.5278, 0]}
        scale={0.0025}
      />
      <mesh
        name="cardboard_box_01_1k006"
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_01_1k006.geometry}
        material={materials.cardboard}
        position={[-0.7928, 3.2186, -1.3727]}
        rotation={[-Math.PI, 1.5351, -Math.PI]}
        scale={0.8339}
      />
      <mesh
        name="imagetostl_mesh"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh.geometry}
        material={materials.metal}
        position={[0.4451, 2.0547, -2.8337]}
        rotation={[0, 1.4929, 0]}
        scale={0.0015}
      />
      <mesh
        name="imagetostl_mesh002"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh002.geometry}
        material={materials.metal}
        position={[0.4451, 2.1123, -2.7648]}
        rotation={[0, 1.3428, 0]}
        scale={0.0015}
      />
      <mesh
        name="imagetostl_mesh001"
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh001.geometry}
        material={materials.metal}
        position={[0.4451, 2.0547, -2.7009]}
        rotation={[0, 1.4929, 0]}
        scale={0.0015}
      />
      <mesh
        name="Router"
        castShadow
        receiveShadow
        geometry={nodes.Router.geometry}
        material={materials.router}
        position={[0.8222, 2.5381, -2.8557]}
        rotation={[Math.PI / 2, 0, 0.2545]}
        scale={0.01}
      />
      <mesh
        name="clester002"
        castShadow
        receiveShadow
        geometry={nodes.clester002.geometry}
        material={materials.router}
        position={[0.7167, 2.5061, -2.6631]}
        rotation={[Math.PI, -1.3282, Math.PI]}
      />
      <mesh
        name="Cube011"
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["vray_Material #31"]}
        position={[0.4138, 3.0927, -2.9087]}
        scale={[0.3988, 0.0158, 0.0874]}
      />
      <mesh
        name="Box001001"
        castShadow
        receiveShadow
        geometry={nodes.Box001001.geometry}
        material={materials["vray_Material #31"]}
        position={[0.4785, 2.2799, -1.4205]}
        rotation={[Math.PI / 2, 0, -2.8903]}
        scale={0.0043}
      />
      <mesh
        name="Box006001"
        castShadow
        receiveShadow
        geometry={nodes.Box006001.geometry}
        material={materials["masaToport.001"]}
        position={[0.4893, 2.4445, -1.4676]}
        rotation={[0, -0.2513, 0]}
        scale={[0.0046, 0.0043, 0.0037]}
      />
      <mesh
        name="desk005"
        castShadow
        receiveShadow
        geometry={nodes.desk005.geometry}
        material={materials.tabla}
        position={[0.5439, 2.3316, -2.7892]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.2196}
      />
      <mesh
        name="desk006"
        castShadow
        receiveShadow
        geometry={nodes.desk006.geometry}
        material={materials.tabla}
        position={[-0.3412, 2.3316, -2.7892]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.2196}
      />
      <mesh
        name="steel_frame_shelves_01_1k003"
        castShadow
        receiveShadow
        geometry={nodes.steel_frame_shelves_01_1k003.geometry}
        material={materials.tabla}
        position={[-0.772, 1.9918, -1.6115]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.7445}
      />
      <mesh
        name="screwdriver007"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver007.geometry}
        material={materials.tabla}
        position={[0.0798, 2.4583, -1.47]}
        rotation={[0, -1.2479, 0]}
        scale={0.0009}
      />
      <mesh
        name="screwdriver008"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver008.geometry}
        material={materials.tabla}
        position={[0.1406, 2.459, -1.5832]}
        rotation={[-Math.PI, 0.506, -Math.PI]}
        scale={0.0009}
      />
      <mesh
        name="screwdriver009"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver009.geometry}
        material={materials.tabla}
        position={[0.2013, 2.4575, -1.644]}
        rotation={[-Math.PI, 1.4502, -Math.PI]}
        scale={0.0009}
      />
      <mesh
        name="lampa_perete006"
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete006.geometry}
        material={materials.lampa_pereti}
        position={[-0.2235, 3.5242, -2.8577]}
        scale={0.0093}
      />
      <mesh
        name="lampa_perete007"
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete007.geometry}
        material={materials.lampa_pereti}
        position={[0.4739, 3.5242, -2.8577]}
        scale={0.0093}
      />
      <mesh
        name="katana003"
        castShadow
        receiveShadow
        geometry={nodes.katana003.geometry}
        material={materials.katarama}
        position={[-0.891, 2.6927, -2.9466]}
        rotation={[3.0316, 0, 0]}
      />
      <mesh
        name="bench_vice_01_1k004"
        castShadow
        receiveShadow
        geometry={nodes.bench_vice_01_1k004.geometry}
        material={materials.merenghina}
        position={[-0.681, 2.469, -1.3608]}
        rotation={[0, 1.309, 0]}
        scale={0.6206}
      />
    </group>
  );
}

useGLTF.preload("/scenes/sez4_room.glb");
