/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Room5(props) {
  const { nodes, materials } = useGLTF("/scenes/sez5_room.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-2.3005, 2.4915, -0.8527]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.0002}
      >
        <group
          position={[-0.001, -0.0004, -0.0007]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <group position={[0, 0, 0.0005]}>
            <group
              position={[0, 394.0781, 0.0005]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_Black_base_0001.geometry}
                material={materials["headphones.001"]}
              />
            </group>
            <group
              position={[-1095.8623, 394.0781, 19.0671]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_Black_base_0001.geometry}
                material={materials["Material.006"]}
              />
            </group>
            <group
              position={[0, 394.0781, 0.0005]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002_Black_base_0001.geometry}
                material={nodes.Cube002_Black_base_0001.material}
              />
            </group>
            <group
              position={[0, 800.4414, 0.0005]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 100, 122.7162]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube003_White_metal_0001.geometry}
                material={materials["headphones.001"]}
              />
            </group>
            <group
              position={[0, 680.5068, 0.0005]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004_Black_base_table_0001.geometry}
                material={materials.premiu_verde}
              />
            </group>
            <group
              position={[0, 311.1328, 1222.3171]}
              rotation={[1.1352, 0, -Math.PI]}
              scale={[-220.5066, -10.5837, -139.8365]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube008_White_metal_0001.geometry}
                material={nodes.Cube008_White_metal_0001.material}
              />
            </group>
            <group
              position={[0, 800.4414, 0.0005]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube009_Black_base_0001.geometry}
                material={materials.red}
              />
            </group>
            <group
              position={[973.79, 2313.2139, -334.7214]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[27.1811, 24.4487, 43.5728]}
            >
              <group
                position={[-0.0376, 0, 1.9494]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[4.0902, 3.679, 2.295]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube013_White_metal_boxes_0001.geometry}
                  material={nodes.Cube013_White_metal_boxes_0001.material}
                />
              </group>
            </group>
            <group
              position={[-1.6592, 2355.1318, -307.2385]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube017_Black_base_0001.geometry}
                material={nodes.Cube017_Black_base_0001.material}
              />
            </group>
            <group
              position={[0, 680.5068, 0.0005]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_Shiny_metal_gold001_0001.geometry}
                material={nodes.Cylinder_Shiny_metal_gold001_0001.material}
              />
            </group>
            <group
              position={[403.2559, 584.835, -48.5615]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 99.8831, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003_Shiny_metal_0001.geometry}
                material={nodes.Cylinder003_Shiny_metal_0001.material}
              />
            </group>
            <group
              position={[-402.1289, 584.835, -48.5615]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 99.8831, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004_Shiny_metal_0001.geometry}
                material={nodes.Cylinder004_Shiny_metal_0001.material}
              />
            </group>
            <group
              position={[403.2559, 619.2979, -48.5625]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder005_Black_base_0001.geometry}
                material={nodes.Cylinder005_Black_base_0001.material}
              />
            </group>
            <group
              position={[-0.0244, 508.8281, 858.8691]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[29.2106, 29.2106, 14.9795]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder010_Black_base_0001.geometry}
                material={nodes.Cylinder010_Black_base_0001.material}
              />
            </group>
            <group
              position={[0, 800.4414, -47.4373]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020_White_metal_0001.geometry}
                material={nodes.Cylinder020_White_metal_0001.material}
              />
            </group>
            <group
              position={[0, 800.4414, 0.0005]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder022_Shiny_metal_0001.geometry}
                material={nodes.Cylinder022_Shiny_metal_0001.material}
              />
            </group>
            <group
              position={[-1.6592, 2300.0742, -100.9058]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[89.0194, 83.1527, 89.0194]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder023_Shiny_metal_0001.geometry}
                material={nodes.Cylinder023_Shiny_metal_0001.material}
              />
            </group>
            <group
              position={[-1.6592, 2494.4268, -100.9058]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[89.8313, 81.5231, 89.8313]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder024_Shiny_metal_0001.geometry}
                material={nodes.Cylinder024_Shiny_metal_0001.material}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder002_Black_base_0001.geometry}
              material={nodes.Cylinder002_Black_base_0001.material}
              position={[-402.1289, 603.374, -1136.5466]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder001_Black_base_0001.geometry}
              material={nodes.Cylinder001_Black_base_0001.material}
              position={[403.2559, 603.374, -1136.5466]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder017_Black_resin_0001.geometry}
              material={nodes.Cylinder017_Black_resin_0001.material}
              position={[-0.0244, 559.4912, -919.0574]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[130.1945, 130.1944, 107.5048]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-1.863, 2.554, -0.7689]}
        rotation={[-Math.PI, 0.3596, -Math.PI]}
        scale={0.0021}
      >
        <group
          position={[47.6582, 64.584, 72.9591]}
          rotation={[-2.7235, -0.5692, -2.9065]}
          scale={9.9832}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028.geometry}
            material={materials["gray_plastic.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028_1.geometry}
            material={materials["display.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028_2.geometry}
            material={materials["monitor_plastic.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028_3.geometry}
            material={materials["logo_monitor_bottom.003"]}
          />
        </group>
        <group
          position={[-16.987, -21.7256, 11.9337]}
          rotation={[-Math.PI / 2, 0, -0.9599]}
          scale={-9.9832}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027.geometry}
            material={materials["monitor_plastic.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_1.geometry}
            material={materials["gray_plastic.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_2.geometry}
            material={materials["keyboard.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_3.geometry}
            material={materials["sensor.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_4.geometry}
            material={materials["socket_USB.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_5.geometry}
            material={materials["socket_power.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_6.geometry}
            material={materials["socket_steel.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_7.geometry}
            material={materials["headphones.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_8.geometry}
            material={materials["logo.001"]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020013.geometry}
        material={materials.metal}
        position={[-2.236, 2.0219, 0.5467]}
        rotation={[Math.PI / 2, 0, -0.4895]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020015.geometry}
        material={materials.metal}
        position={[-2.1325, 2.0227, 0.4329]}
        rotation={[Math.PI / 2, 0, -0.624]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020016.geometry}
        material={materials.metal}
        position={[-2.1382, 2.0632, 0.559]}
        rotation={[Math.PI / 2, 0, 2.0289]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020014.geometry}
        material={materials.metal}
        position={[-2.1307, 2.0249, 0.5133]}
        rotation={[Math.PI / 2, 0, -0.624]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020018.geometry}
        material={materials.metal}
        position={[-2.2336, 2.1064, 0.4265]}
        rotation={[Math.PI / 2, 0, -0.9731]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020020.geometry}
        material={materials.metal}
        position={[-1.338, 2.3045, -0.7649]}
        rotation={[Math.PI / 2, 0, -1.5774]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020017.geometry}
        material={materials.metal}
        position={[-2.3166, 2.0632, 0.3113]}
        rotation={[Math.PI / 2, 0, -1.4751]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020019.geometry}
        material={materials.metal}
        position={[-1.3716, 2.3015, -0.6597]}
        rotation={[Math.PI / 2, 0, -1.4428]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020021.geometry}
        material={materials.metal}
        position={[-1.305, 2.3428, -0.7323]}
        rotation={[Math.PI / 2, 0, 1.0755]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020022.geometry}
        material={materials.metal}
        position={[-2.5354, 2.5196, -0.2744]}
        rotation={[Math.PI / 2, 0, -0.0559]}
        scale={0.0002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-3.1, 3, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials.cardboard}
        position={[-2, 2.0046, 0]}
        scale={[1, 0.01, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube052.geometry}
        material={nodes.Cube052.material}
        position={[-2, 3, -1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials["white.Smoke"]}
        position={[-2.8, 3, -0.9]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 1, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_01_1k008.geometry}
        material={materials.cardboard}
        position={[-1.5414, 2.0098, -0.7925]}
        scale={0.8339}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh004.geometry}
        material={materials.metal}
        position={[-2.2152, 2.0547, -0.2366]}
        rotation={[-Math.PI, 0.5872, -Math.PI]}
        scale={0.0015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_01_1k009.geometry}
        material={materials.cardboard}
        position={[-1.2078, 1.9953, -0.7839]}
        scale={0.8339}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh003.geometry}
        material={materials.metal}
        position={[-2.3312, 2.0547, -0.3014]}
        rotation={[-Math.PI, 0.5872, -Math.PI]}
        scale={0.0015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tool_box1_Tool_box_polymer_0002.geometry}
        material={materials.box_portocala}
        position={[-2.2798, 2.1298, -0.7134]}
        scale={0.5276}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh005.geometry}
        material={materials.metal}
        position={[-2.271, 2.1123, -0.2678]}
        rotation={[-Math.PI, 0.7373, -Math.PI]}
        scale={0.0015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box001002.geometry}
        material={materials["vray_Material #31"]}
        position={[-1.4677, 2.3148, 0.6377]}
        rotation={[Math.PI / 2, 0, -2.8903]}
        scale={0.0043}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete008.geometry}
        material={materials.lampa_pereti}
        position={[-2.2249, 3.5242, -0.8578]}
        scale={0.0093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete009.geometry}
        material={materials.lampa_pereti}
        position={[-1.5275, 3.5242, -0.8578]}
        scale={0.0093}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.surusurubelnita005.geometry}
        material={materials.lampa_pereti}
        position={[-1.1828, 2.5107, -0.7713]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={1.0594}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.desk007.geometry}
        material={materials.tabla}
        position={[-1.3525, 2.3316, -0.8061]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.1743, 0.2196, 0.2196]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.desk008.geometry}
        material={materials.tabla}
        position={[-2.1424, 2.3316, -0.8061]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.2196}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screwdriver010.geometry}
        material={materials.tabla}
        position={[-1.0828, 2.4945, 0.7045]}
        rotation={[0, -1.2479, 0]}
        scale={0.0009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.desk009.geometry}
        material={materials.tabla}
        position={[-2.3976, 2.3316, -0.2629]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.1743, 0.2196, 0.2196]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Router001.geometry}
        material={materials.router}
        position={[-1.3964, 2.5381, -0.8636]}
        rotation={[Math.PI / 2, 0, -0.5393]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clester003.geometry}
        material={materials.router}
        position={[-1.0565, 2.4911, 0.8909]}
        rotation={[Math.PI, -1.035, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screwdriver011.geometry}
        material={materials.router}
        position={[-1.022, 2.492, 0.5912]}
        rotation={[-Math.PI, 0.506, -Math.PI]}
        scale={0.0009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench_vice_01_1k005.geometry}
        material={materials.merenghina}
        position={[-2.3936, 2.4957, -0.0022]}
        scale={0.6206}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box006002.geometry}
        material={materials.masaToport2}
        position={[-1.4569, 2.4782, 0.5907]}
        rotation={[0, -0.2513, 0]}
        scale={[0.0046, 0.0043, 0.0037]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.katana004.geometry}
        material={materials.katarama}
        position={[-2.2397, 2.6927, -0.8369]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={-0.3484}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Drill_01_1k004.geometry}
        material={materials.boromiro_masina}
        position={[-1.7803, 2.4843, 0.352]}
        rotation={[0, 1.4105, -0.089]}
        scale={1.2866}
      />
    </group>
  );
}

useGLTF.preload("/scenes/sez5_room.glb");
