/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Room3(props) {
  const { nodes, materials } = useGLTF("/scenes/sez3_room.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        position={[2.3098, 0.3362, -2.37]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          name="Tool_boxfbx"
          position={[-0.4257, 0.2174, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Tool_box1_Tool_box_polymer_0"
            castShadow
            receiveShadow
            geometry={nodes.Tool_box1_Tool_box_polymer_0.geometry}
            material={materials.box_portocala}
            position={[0.2464, -0.112, 0.1134]}
            scale={0.5276}
          />
          <mesh
            name="Tool_box1_Tool_box_plastic_0"
            castShadow
            receiveShadow
            geometry={nodes.Tool_box1_Tool_box_plastic_0.geometry}
            material={materials["sensor.001"]}
            position={[0.2464, -0.112, 0.1134]}
            scale={0.5276}
          />
        </group>
      </group>
      <group
        name="Group003002"
        position={[1.4325, 0.2542, -2.3673]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.0217, 0.0217, 0.0256]}
      >
        <group name="Group001002" position={[-13.5455, -0.1372, 0]}>
          <mesh
            name="Wheel002002"
            castShadow
            receiveShadow
            geometry={nodes.Wheel002002.geometry}
            material={materials["headphones.001"]}
            position={[0.5969, -0.4058, 3.3731]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={-1}
          />
          <mesh
            name="Wheel003002"
            castShadow
            receiveShadow
            geometry={nodes.Wheel003002.geometry}
            material={materials["headphones.001"]}
            position={[0.6025, -0.4058, -3.3731]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Veshalka001002"
            castShadow
            receiveShadow
            geometry={nodes.Veshalka001002.geometry}
            material={materials.metal}
            position={[0.4183, -0.0548, 3.1405]}
            rotation={[1.5583, 0.9486, -1.5554]}
            scale={-0.0917}
          />
        </group>
        <group name="Group002002" position={[14.4895, -0.1372, 0]}>
          <mesh
            name="Wheel002"
            castShadow
            receiveShadow
            geometry={nodes.Wheel002.geometry}
            material={materials["headphones.001"]}
            position={[-0.6025, -0.4058, -3.3731]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={-1}
          />
          <mesh
            name="Wheel001002"
            castShadow
            receiveShadow
            geometry={nodes.Wheel001002.geometry}
            material={materials["headphones.001"]}
            position={[-0.5969, -0.4058, 3.3731]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
          />
          <mesh
            name="Veshalka002"
            castShadow
            receiveShadow
            geometry={nodes.Veshalka002.geometry}
            material={materials.metal}
            position={[-0.4183, -0.0892, 3.1405]}
            rotation={[-1.5833, 0.9486, -1.5554]}
            scale={0.0917}
          />
        </group>
        <mesh
          name="Line001004"
          castShadow
          receiveShadow
          geometry={nodes.Line001004.geometry}
          material={materials.cardboard}
          position={[-0.5984, 1.7409, -1.6991]}
        />
        <mesh
          name="Line001005"
          castShadow
          receiveShadow
          geometry={nodes.Line001005.geometry}
          material={materials.cardboard}
          position={[-0.5984, 1.7409, -1.6991]}
        />
      </group>
      <mesh
        name="Perfil2020005"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020005.geometry}
        material={materials.metal}
        position={[1.515, 1.015, -2.3577]}
        rotation={[Math.PI / 2, -0.1414, -Math.PI / 2]}
        scale={0.0002}
      />
      <mesh
        name="Perfil2020004"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020004.geometry}
        material={materials.metal}
        position={[1.4142, 0.993, -2.3577]}
        rotation={[Math.PI / 2, 0, -1.878]}
        scale={0.0002}
      />
      <mesh
        name="Perfil2020006"
        castShadow
        receiveShadow
        geometry={nodes.Perfil2020006.geometry}
        material={materials.metal}
        position={[1.1681, 0.7353, -1.696]}
        rotation={[Math.PI / 2, 0, 2.6529]}
        scale={0.0002}
      />
      <mesh
        name="Cube004"
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[0, 1, -2]}
      />
      <mesh
        name="Cube017"
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials.cardboard}
        position={[2, 0.0675, -2]}
        scale={[1, 0.0312, 1]}
      />
      <mesh
        name="Cube021"
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[2, 1, -3.094]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name="suportShula"
        castShadow
        receiveShadow
        geometry={nodes.suportShula.geometry}
        material={materials.red}
        position={[1.0731, 0.9432, -1.1669]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.0213}
      />
      <mesh
        name="Cube010"
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["white.Smoke"]}
        position={[1.09, 1, -2.8]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.2, 1, 0.1]}
      />
      <mesh
        name="suportShula001"
        castShadow
        receiveShadow
        geometry={nodes.suportShula001.geometry}
        material={materials.red}
        position={[1.0731, 0.9432, -1.4489]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.0213}
      />
      <mesh
        name="screwdriver006"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver006.geometry}
        material={nodes.screwdriver006.material}
        position={[1.0837, 1.0215, -1.1667]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.0009}
      />
      <mesh
        name="cardboard_box_01_1k004"
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_01_1k004.geometry}
        material={materials.cardboard}
        position={[1.2, 1.328, -2.4043]}
        scale={0.8339}
      />
      <mesh
        name="bend1002"
        castShadow
        receiveShadow
        geometry={nodes.bend1002.geometry}
        material={materials.router}
        position={[1.2289, 0.5835, -1.5467]}
        scale={0.0055}
      />
      <mesh
        name="lampa_perete004"
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete004.geometry}
        material={materials.lampa_pereti}
        position={[1.129, 1.3954, -1.65]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.0093}
      />
      <mesh
        name="lampa_perete005"
        castShadow
        receiveShadow
        geometry={nodes.lampa_perete005.geometry}
        material={materials.lampa_pereti}
        position={[2.4474, 1.3954, -2.8599]}
        scale={0.0093}
      />
      <mesh
        name="surusurubelnita004"
        castShadow
        receiveShadow
        geometry={nodes.surusurubelnita004.geometry}
        material={materials.lampa_pereti}
        position={[1.0786, 0.8892, -1.1432]}
        rotation={[Math.PI / 2, 1.1903, 0]}
        scale={0.828}
      />
      <mesh
        name="clester001"
        castShadow
        receiveShadow
        geometry={nodes.clester001.geometry}
        material={materials.tabla}
        position={[2.1119, 0.6162, -1.5078]}
        rotation={[Math.PI, -0.6196, Math.PI]}
      />
      <mesh
        name="steel_frame_shelves_01_1k002"
        castShadow
        receiveShadow
        geometry={nodes.steel_frame_shelves_01_1k002.geometry}
        material={materials.tabla}
        position={[1.4379, 0.1012, -2.3749]}
        scale={0.7445}
      />
      <mesh
        name="desk003"
        castShadow
        receiveShadow
        geometry={nodes.desk003.geometry}
        material={materials.tabla}
        position={[2.1829, 0.4431, -1.5]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.2196}
      />
      <mesh
        name="desk004"
        castShadow
        receiveShadow
        geometry={nodes.desk004.geometry}
        material={materials.tabla}
        position={[2.5638, 0.4431, -1.5435]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.2196}
      />
      <mesh
        name="screwdriver004"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver004.geometry}
        material={materials.tabla}
        position={[2.5666, 0.618, -1.2012]}
        rotation={[0, 1.1641, 0]}
        scale={0.0008}
      />
      <mesh
        name="screwdriver005"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver005.geometry}
        material={materials.tabla}
        position={[2.2726, 0.618, -1.2012]}
        rotation={[0, -1.2479, 0]}
        scale={0.0009}
      />
      <mesh
        name="bench_vice_01_1k003"
        castShadow
        receiveShadow
        geometry={nodes.bench_vice_01_1k003.geometry}
        material={materials.merenghina}
        position={[1.3361, 0.7399, -1.111]}
        scale={0.6206}
      />
      <mesh
        name="Drill_01_1k003"
        castShadow
        receiveShadow
        geometry={nodes.Drill_01_1k003.geometry}
        material={materials.boromiro_masina}
        position={[2.0585, 0.6129, -1.2311]}
        rotation={[Math.PI, 1.2118, 3.0634]}
        scale={1.2866}
      />
    </group>
  );
}

useGLTF.preload("/scenes/sez3_room.glb");
